run:
  go: 1.23

linters:
  presets:
    - bugs
    - comment
  disable:
    - godox # Annoying, we have too many TODOs at the moment :p
    - musttag # We do not want to force annotating every field name.
    - errorlint # Too many false positives
issues:
  exclude-rules:
    - path: benchmarks
      linters:
        - gosec
        - dupword
    - path: tests
      linters:
        - dupword
    - path: _test\.go
      linters:
        - dupword
linters-settings:
  gosec:
    excludes:
      - G115  # Potential integer overflow when converting between integer types
