name: Lint and Test

on:
  pull_request:
    branches: dev

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-15, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get sources
        uses: actions/checkout@v4

      - name: Set up Go 1.23.3
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.3'

      - name: Run go mod tidy
        run: go mod tidy

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.62.0
          args: --timeout=500s
          skip-cache: true

      - name: Run govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: 1.23
          go-package: ./...

      - name: Run tests
        run: go test -timeout 15m -v ./...

      - name: Run tests with race check
        if: runner.os != 'Windows'
        run: go test -race -v ./tests

  Fuzzing:
    runs-on: ubuntu-latest
    steps:
    - name: Build Fuzzers
      id: build
      uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@master
      with:
        oss-fuzz-project-name: 'gluon'
        language: go
    - name: Run Fuzzers
      uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@master
      with:
        oss-fuzz-project-name: 'gluon'
        language: go
        fuzz-seconds: 300
    - name: Upload Crash
      uses: actions/upload-artifact@v3
      if: failure() && steps.build.outcome == 'success'
      with:
        name: artifacts
        path: ./out/artifacts
